POST  http://localhost:8000/refresh
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ0ZXN0IiwiaWF0IjoxNjI1MDQwNTc0LCJuYmYiOjE2MjUwNDA1NzQsImp0aSI6ImJiYjc4MzhhLTg2ZWEtNDBmNy04YjM3LWZmODVjYmNhNTUzZiIsImV4cCI6MTYyNTA0MTQ3NCwidHlwZSI6ImFjY2VzcyIsImZyZXNoIjpmYWxzZX0.N_l4mNcbuu4wdmBJiS-qbLT1X-DCOuFjLfJccosRF80

